set_property IOSTANDARD LVCMOS33 [get_ports capturetrig0]
set_property IOSTANDARD LVCMOS33 [get_ports capturetrig1]
set_property PACKAGE_PIN R10 [get_ports capturetrig0]
set_property PACKAGE_PIN P10 [get_ports capturetrig1]

set_property IOSTANDARD LVCMOS33 [get_ports UART_0_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports UART_0_txd]
set_property PACKAGE_PIN L15 [get_ports UART_0_rxd]
set_property PACKAGE_PIN M15 [get_ports UART_0_txd]
set_property PULLUP true [get_ports UART_0_rxd]
set_property PULLUP true [get_ports UART_0_txd]

set_property IOSTANDARD LVCMOS33 [get_ports {gpio_0_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_0_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_0_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_0_tri_io[0]}]
set_property PACKAGE_PIN K13 [get_ports {gpio_0_tri_io[0]}]
set_property PACKAGE_PIN L13 [get_ports {gpio_0_tri_io[1]}]
set_property PACKAGE_PIN N13 [get_ports {gpio_0_tri_io[2]}]
set_property PACKAGE_PIN N14 [get_ports {gpio_0_tri_io[3]}]
set_property PULLUP true [get_ports {gpio_0_tri_io[1]}]
set_property PULLUP true [get_ports {gpio_0_tri_io[3]}]

set_property PACKAGE_PIN P9 [get_ports {gpio_0_tri_io[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_0_tri_io[4]}]
set_property PACKAGE_PIN N7 [get_ports {gpio_0_tri_io[5]}]
set_property PACKAGE_PIN P10 [get_ports {gpio_0_tri_io[6]}]
set_property PACKAGE_PIN N8 [get_ports {gpio_0_tri_io[7]}]
set_property PACKAGE_PIN M9 [get_ports {gpio_0_tri_io[8]}]
set_property PACKAGE_PIN R11 [get_ports {gpio_0_tri_io[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_0_tri_io[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_0_tri_io[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_0_tri_io[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_0_tri_io[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_0_tri_io[9]}]
set_property PACKAGE_PIN F14 [get_ports {gpio_0_tri_io[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_0_tri_io[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_0_tri_io[11]}]
set_property PACKAGE_PIN F14 [get_ports {gpio_0_tri_io[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_0_tri_io[12]}]
set_property PACKAGE_PIN F13 [get_ports {gpio_0_tri_io[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_0_tri_io[13]}]


set_property PACKAGE_PIN F13 [get_ports {gpio_0_tri_io[11]}]
set_property PACKAGE_PIN N9 [get_ports TTC0_WAVE0_OUT]
set_property PACKAGE_PIN M10 [get_ports TTC0_WAVE1_OUT]
set_property IOSTANDARD LVCMOS33 [get_ports TTC0_WAVE0_OUT]
set_property IOSTANDARD LVCMOS33 [get_ports TTC0_WAVE1_OUT]

set_property PACKAGE_PIN P13 [get_ports iic_0_scl_io]
set_property PACKAGE_PIN P14 [get_ports iic_0_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports iic_0_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports iic_0_sda_io]
