



set_property PACKAGE_PIN R12 [get_ports SDIO_0_cdn]
set_property IOSTANDARD LVCMOS33 [get_ports SDIO_0_cdn]
set_property PACKAGE_PIN N11 [get_ports {sdio_0_data_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sdio_0_data_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sdio_0_data_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sdio_0_data_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sdio_0_data_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports SDIO_0_wp]
set_property IOSTANDARD LVCMOS33 [get_ports {SDIO_0_busvolt[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SDIO_0_busvolt[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SDIO_0_busvolt[0]}]
set_property PACKAGE_PIN E11 [get_ports {SDIO_0_busvolt[2]}]
set_property PACKAGE_PIN E12 [get_ports {SDIO_0_busvolt[1]}]
set_property PACKAGE_PIN E13 [get_ports {SDIO_0_busvolt[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports SDIO_0_buspow]
set_property IOSTANDARD LVCMOS33 [get_ports sdio_0_cmd_io]
set_property IOSTANDARD LVCMOS33 [get_ports SDIO_0_led]
set_property PACKAGE_PIN P14 [get_ports sdio_0_cmd_io]
set_property PACKAGE_PIN F14 [get_ports SDIO_0_led]


set_property PACKAGE_PIN F15 [get_ports SDIO_0_buspow]
set_property SLEW FAST [get_ports {SDIO_0_busvolt[2]}]
set_property SLEW FAST [get_ports {SDIO_0_busvolt[1]}]
set_property SLEW FAST [get_ports {SDIO_0_busvolt[0]}]
set_property SLEW SLOW [get_ports {sdio_0_data_io[3]}]
set_property SLEW SLOW [get_ports {sdio_0_data_io[2]}]
set_property SLEW SLOW [get_ports {sdio_0_data_io[1]}]
set_property SLEW SLOW [get_ports {sdio_0_data_io[0]}]
set_property SLEW SLOW [get_ports SDIO_0_buspow]

set_property PACKAGE_PIN R15 [get_ports {sdio_0_data_io[2]}]
set_property PACKAGE_PIN P15 [get_ports {sdio_0_data_io[1]}]


set_property PACKAGE_PIN P13 [get_ports {sdio_0_data_io[3]}]
set_property SLEW SLOW [get_ports sdio_0_cmd_io]


set_property PACKAGE_PIN R13 [get_ports SDIO_0_wp]

set_property IOSTANDARD LVCMOS33 [get_ports {BUFH_O_1[0]}]
set_property SLEW FAST [get_ports {BUFH_O_1[0]}]
set_property PACKAGE_PIN N12 [get_ports {BUFH_O_1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports SDIO_0_clk_fb]


set_property PULLDOWN true [get_ports SDIO_0_wp]

set_property PULLUP true [get_ports {sdio_0_data_io[3]}]
set_property PULLUP true [get_ports {sdio_0_data_io[2]}]
set_property PULLUP true [get_ports {sdio_0_data_io[1]}]
set_property PULLUP true [get_ports {sdio_0_data_io[0]}]
set_property PULLUP true [get_ports sdio_0_cmd_io]

set_property PACKAGE_PIN P13 [get_ports {sdio_1_data_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sdio_1_data_io[3]}]
set_property PULLUP true [get_ports {sdio_1_data_io[3]}]
set_property PACKAGE_PIN R15 [get_ports {sdio_1_data_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sdio_1_data_io[2]}]
set_property PULLUP true [get_ports {sdio_1_data_io[2]}]
set_property PACKAGE_PIN P15 [get_ports {sdio_1_data_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sdio_1_data_io[1]}]
set_property PULLUP true [get_ports {sdio_1_data_io[1]}]
set_property PACKAGE_PIN N11 [get_ports {sdio_1_data_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sdio_1_data_io[0]}]
set_property PULLUP true [get_ports {sdio_1_data_io[0]}]
set_property PACKAGE_PIN N12 [get_ports SDIO_1_clk]
set_property IOSTANDARD LVCMOS33 [get_ports SDIO_1_clk]
set_property PULLUP true [get_ports SDIO_1_clk]
set_property PULLUP true [get_ports SDIO_1_clk_fb]

set_property PACKAGE_PIN N13 [get_ports {SDIO_1_busvolt[2]}]
set_property PACKAGE_PIN N14 [get_ports {SDIO_1_busvolt[1]}]
set_property PACKAGE_PIN L15 [get_ports {SDIO_1_busvolt[0]}]
set_property PACKAGE_PIN M15 [get_ports SDIO_1_buspow]
set_property PACKAGE_PIN R12 [get_ports SDIO_1_cdn]
set_property IOSTANDARD LVCMOS33 [get_ports SDIO_1_cdn]
set_property PACKAGE_PIN P14 [get_ports sdio_1_cmd_io]
set_property IOSTANDARD LVCMOS33 [get_ports sdio_1_cmd_io]
set_property PULLUP true [get_ports sdio_1_cmd_io]
set_property PACKAGE_PIN K13 [get_ports SDIO_1_led]
set_property PACKAGE_PIN R13 [get_ports SDIO_1_wp]
set_property IOSTANDARD LVCMOS33 [get_ports SDIO_1_wp]
set_property PULLDOWN true [get_ports SDIO_1_wp]
set_property PULLUP true [get_ports sdio_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sdio_clk]
set_property PACKAGE_PIN N12 [get_ports sdio_clk]
set_property IOSTANDARD LVCMOS33 [get_ports SDIO_1_led]
set_property IOSTANDARD LVCMOS33 [get_ports SDIO_1_buspow]
set_property IOSTANDARD LVCMOS33 [get_ports {SDIO_1_busvolt[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SDIO_1_busvolt[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SDIO_1_busvolt[0]}]
