set_property IOSTANDARD LVCMOS33 [get_ports capturetrig0]
set_property IOSTANDARD LVCMOS33 [get_ports capturetrig1]
set_property PACKAGE_PIN R10 [get_ports capturetrig0]
set_property PACKAGE_PIN P10 [get_ports capturetrig1]

set_property IOSTANDARD LVCMOS33 [get_ports UART_0_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports UART_0_txd]
set_property PACKAGE_PIN L15 [get_ports UART_0_rxd]
set_property PACKAGE_PIN M15 [get_ports UART_0_txd]
set_property PULLUP true [get_ports UART_0_rxd]
set_property PULLUP true [get_ports UART_0_txd]

set_property IOSTANDARD LVCMOS33 [get_ports {gpio_0_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_0_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_0_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_0_tri_io[0]}]
set_property PACKAGE_PIN K13 [get_ports {gpio_0_tri_io[0]}]
set_property PACKAGE_PIN L13 [get_ports {gpio_0_tri_io[1]}]
set_property PACKAGE_PIN N13 [get_ports {gpio_0_tri_io[2]}]
set_property PACKAGE_PIN N14 [get_ports {gpio_0_tri_io[3]}]
set_property PULLUP true [get_ports {gpio_0_tri_io[1]}]
set_property PULLUP true [get_ports {gpio_0_tri_io[3]}]
