/*
 * inputcapture.c
 *
 *  Created on: May 28, 2018
 *      Author: Jerome Pare-Lepine
 *      Notes: Generally used to measure rotational speeds like the turbine's RPM
 *      and the car axle's RPM. It basically measures the time between two input
 *      events.
 */

//==============================================================================
// INCLUDES
//==============================================================================
#include "inputcapture.h"
#include "interrupts.h"


void InitTmrCtrs(XTmrCtr *Inst)
/*
* \brief       Initializes a timer/counter struct instance using the autogenerated bsp config
*              and carry out the register inits of the peripheral.
*
* \param[in]   Inst         - Pointer to the XTmrCtr peripheral struct instance to be
*                             initialized.
*/
{
	XTmrCtr_Config *TmpConf;
	u32 csRegValue = 0;

	TmpConf = XTmrCtr_LookupConfig(DEVICE_TMR_0);
	XTmrCtr_CfgInitialize(Inst, TmpConf, XPAR_AXI_TIMER_0_BASEADDR);

	XTmrCtr_SetOptions(Inst, DEVICE_TMR_0,
				XTC_INT_MODE_OPTION);

	/* For debug purposes */
	csRegValue = XTmrCtr_GetControlStatusReg(XPAR_AXI_TIMER_0_BASEADDR, DEVICE_TMR_0);

	/* Clear the interrupt bit, sets mode to capture, set to external capture
	 * and enable the peripheral.  */
	csRegValue |= XTC_CSR_INT_OCCURED_MASK \
			| XTC_CSR_EXT_CAPTURE_MASK \
			| XTC_CSR_CAPTURE_MODE_MASK \
			| XTC_CSR_ENABLE_TMR_MASK;
	XTmrCtr_SetControlStatusReg(XPAR_AXI_TIMER_0_BASEADDR, DEVICE_TMR_0, csRegValue);

	XTmrCtr_SetOptions(Inst, DEVICE_TMR_1,
				XTC_INT_MODE_OPTION);

	/* For debug purposes */
	csRegValue = XTmrCtr_GetControlStatusReg(XPAR_AXI_TIMER_0_BASEADDR, DEVICE_TMR_1);
	csRegValue |= XTC_CSR_INT_OCCURED_MASK \
			| XTC_CSR_EXT_CAPTURE_MASK \
			| XTC_CSR_CAPTURE_MODE_MASK \
			| XTC_CSR_ENABLE_TMR_MASK;
	XTmrCtr_SetControlStatusReg(XPAR_AXI_TIMER_0_BASEADDR, DEVICE_TMR_1, csRegValue);

	/* Kick off the peripherals */
	XTmrCtr_Start(Inst, DEVICE_TMR_0);
	XTmrCtr_Start(Inst, DEVICE_TMR_1);

}


void InitTmrCtrInterrupts(XTmrCtr *Inst)
/*
* \brief       Registers the peripheral's interrupt handlers to its peripheral
*              instance struct. Also lists it to be registered to the Interrupt
*              Controller.
*
* \param[in]   Inst         - Pointer to the XTmrCtr peripheral struct
*                             instance for which the interrupts are to be setup.
*/
{
	/* Register an interrupt handler to the peripheral's instance
	 * object */
	XTmrCtr_SetHandler(Inst, (void *) TmrCtrHandler, (void *)Inst);

	/* Add the instance, its interrupt handler and vector ID to the handler
	 * initialization table. */
	AddHandler2InitTable(Inst, XPAR_FABRIC_AXI_TIMER_0_INTERRUPT_INTR,
			(Xil_InterruptHandler) XTmrCtr_InterruptHandler,
			(void *)&ExceptionHandlers);

}
