# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Chinook-ELE/ZynqWorkspace/SensTel2_emio_NNip/nn_ip_addition/nn_ip_addition.srcs/sources_1/bd/System/ip/System_NN_1_0/System_NN_1_0.xci
# IP: The module: 'System_NN_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Chinook-ELE/ZynqWorkspace/SensTel2_emio_NNip/nn_ip_addition/nn_ip_addition.srcs/sources_1/bd/System/ip/System_NN_1_0/src/L2_DSP_THIRD_ADD/L2_DSP_THIRD_ADD/L2_DSP_THIRD_ADD.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==L2_DSP_THIRD_ADD || ORIG_REF_NAME==L2_DSP_THIRD_ADD} -quiet] -quiet

# IP: c:/Users/Chinook-ELE/ZynqWorkspace/SensTel2_emio_NNip/nn_ip_addition/nn_ip_addition.srcs/sources_1/bd/System/ip/System_NN_1_0/src/L2_DSP_SECOND_ADD/L2_DSP_SECOND_ADD/L2_DSP_SECOND_ADD.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==L2_DSP_SECOND_ADD || ORIG_REF_NAME==L2_DSP_SECOND_ADD} -quiet] -quiet

# IP: c:/Users/Chinook-ELE/ZynqWorkspace/SensTel2_emio_NNip/nn_ip_addition/nn_ip_addition.srcs/sources_1/bd/System/ip/System_NN_1_0/src/L2_DSP_FIRST_ADD/L2_DSP_FIRST_ADD/L2_DSP_FIRST_ADD.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==L2_DSP_FIRST_ADD || ORIG_REF_NAME==L2_DSP_FIRST_ADD} -quiet] -quiet

# IP: c:/Users/Chinook-ELE/ZynqWorkspace/SensTel2_emio_NNip/nn_ip_addition/nn_ip_addition.srcs/sources_1/bd/System/ip/System_NN_1_0/src/L2_DSP_INV_ADD/L2_DSP_INV_ADD/L2_DSP_INV_ADD.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==L2_DSP_INV_ADD || ORIG_REF_NAME==L2_DSP_INV_ADD} -quiet] -quiet

# IP: c:/Users/Chinook-ELE/ZynqWorkspace/SensTel2_emio_NNip/nn_ip_addition/nn_ip_addition.srcs/sources_1/bd/System/ip/System_NN_1_0/src/L1_DSP_ADD/L1_DSP_ADD/L1_DSP_ADD.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==L1_DSP_ADD || ORIG_REF_NAME==L1_DSP_ADD} -quiet] -quiet

# IP: c:/Users/Chinook-ELE/ZynqWorkspace/SensTel2_emio_NNip/nn_ip_addition/nn_ip_addition.srcs/sources_1/bd/System/ip/System_NN_1_0/src/L1_DSP_MULT_ADD_BIAS/L1_DSP_MULT_ADD_BIAS/L1_DSP_MULT_ADD_BIAS.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==L1_DSP_MULT_ADD_BIAS || ORIG_REF_NAME==L1_DSP_MULT_ADD_BIAS} -quiet] -quiet

# IP: c:/Users/Chinook-ELE/ZynqWorkspace/SensTel2_emio_NNip/nn_ip_addition/nn_ip_addition.srcs/sources_1/bd/System/ip/System_NN_1_0/src/L1_DSP_MULT_ADD/L1_DSP_MULT_ADD/L1_DSP_MULT_ADD.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==L1_DSP_MULT_ADD || ORIG_REF_NAME==L1_DSP_MULT_ADD} -quiet] -quiet

# IP: c:/Users/Chinook-ELE/ZynqWorkspace/SensTel2_emio_NNip/nn_ip_addition/nn_ip_addition.srcs/sources_1/bd/System/ip/System_NN_1_0/src/L1_DSP_MULT/L1_DSP_MULT/L1_DSP_MULT.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==L1_DSP_MULT || ORIG_REF_NAME==L1_DSP_MULT} -quiet] -quiet

# IP: c:/Users/Chinook-ELE/ZynqWorkspace/SensTel2_emio_NNip/nn_ip_addition/nn_ip_addition.srcs/sources_1/bd/System/ip/System_NN_1_0/System_NN_1_0.xci
# IP: The module: 'System_NN_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Chinook-ELE/ZynqWorkspace/SensTel2_emio_NNip/nn_ip_addition/nn_ip_addition.srcs/sources_1/bd/System/ip/System_NN_1_0/src/L2_DSP_THIRD_ADD/L2_DSP_THIRD_ADD/L2_DSP_THIRD_ADD.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==L2_DSP_THIRD_ADD || ORIG_REF_NAME==L2_DSP_THIRD_ADD} -quiet] -quiet

# IP: c:/Users/Chinook-ELE/ZynqWorkspace/SensTel2_emio_NNip/nn_ip_addition/nn_ip_addition.srcs/sources_1/bd/System/ip/System_NN_1_0/src/L2_DSP_SECOND_ADD/L2_DSP_SECOND_ADD/L2_DSP_SECOND_ADD.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==L2_DSP_SECOND_ADD || ORIG_REF_NAME==L2_DSP_SECOND_ADD} -quiet] -quiet

# IP: c:/Users/Chinook-ELE/ZynqWorkspace/SensTel2_emio_NNip/nn_ip_addition/nn_ip_addition.srcs/sources_1/bd/System/ip/System_NN_1_0/src/L2_DSP_FIRST_ADD/L2_DSP_FIRST_ADD/L2_DSP_FIRST_ADD.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==L2_DSP_FIRST_ADD || ORIG_REF_NAME==L2_DSP_FIRST_ADD} -quiet] -quiet

# IP: c:/Users/Chinook-ELE/ZynqWorkspace/SensTel2_emio_NNip/nn_ip_addition/nn_ip_addition.srcs/sources_1/bd/System/ip/System_NN_1_0/src/L2_DSP_INV_ADD/L2_DSP_INV_ADD/L2_DSP_INV_ADD.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==L2_DSP_INV_ADD || ORIG_REF_NAME==L2_DSP_INV_ADD} -quiet] -quiet

# IP: c:/Users/Chinook-ELE/ZynqWorkspace/SensTel2_emio_NNip/nn_ip_addition/nn_ip_addition.srcs/sources_1/bd/System/ip/System_NN_1_0/src/L1_DSP_ADD/L1_DSP_ADD/L1_DSP_ADD.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==L1_DSP_ADD || ORIG_REF_NAME==L1_DSP_ADD} -quiet] -quiet

# IP: c:/Users/Chinook-ELE/ZynqWorkspace/SensTel2_emio_NNip/nn_ip_addition/nn_ip_addition.srcs/sources_1/bd/System/ip/System_NN_1_0/src/L1_DSP_MULT_ADD_BIAS/L1_DSP_MULT_ADD_BIAS/L1_DSP_MULT_ADD_BIAS.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==L1_DSP_MULT_ADD_BIAS || ORIG_REF_NAME==L1_DSP_MULT_ADD_BIAS} -quiet] -quiet

# IP: c:/Users/Chinook-ELE/ZynqWorkspace/SensTel2_emio_NNip/nn_ip_addition/nn_ip_addition.srcs/sources_1/bd/System/ip/System_NN_1_0/src/L1_DSP_MULT_ADD/L1_DSP_MULT_ADD/L1_DSP_MULT_ADD.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==L1_DSP_MULT_ADD || ORIG_REF_NAME==L1_DSP_MULT_ADD} -quiet] -quiet

# IP: c:/Users/Chinook-ELE/ZynqWorkspace/SensTel2_emio_NNip/nn_ip_addition/nn_ip_addition.srcs/sources_1/bd/System/ip/System_NN_1_0/src/L1_DSP_MULT/L1_DSP_MULT/L1_DSP_MULT.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==L1_DSP_MULT || ORIG_REF_NAME==L1_DSP_MULT} -quiet] -quiet
