webtalk_init -webtalk_dir C:\\Users\\Chinook-ELE\\ZynqWorkspace\\SensTel2_emio_NNip\\nn_ip_addition\\rtos_emio_port_NN_rev4_but_after_rev5\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-08-23 23:53:12" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "q3ke43vdnk825ae42014t56uvl" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.4_2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2712 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.438 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1534860250295" -context "sdk\\\\bsp/1534860250295"
webtalk_add_data -client sdk -key hwid -value "1530299860208" -context "sdk\\\\bsp/1534860250295"
webtalk_add_data -client sdk -key os -value "freertos901_xilinx" -context "sdk\\\\bsp/1534860250295"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1534860250295"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1534860250295"
webtalk_add_data -client sdk -key uid -value "1534860633340" -context "sdk\\\\bsp/1534860633340"
webtalk_add_data -client sdk -key hwid -value "1530299860208" -context "sdk\\\\bsp/1534860633340"
webtalk_add_data -client sdk -key os -value "freertos901_xilinx" -context "sdk\\\\bsp/1534860633340"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1534860633340"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1534860633340"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1535061192852"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1535061192852"
webtalk_add_data -client sdk -key BootgenCount -value "4" -context "sdk\\\\bsp/1535061192852"
webtalk_add_data -client sdk -key DebugCount -value "21" -context "sdk\\\\bsp/1535061192852"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1535061192852"
webtalk_add_data -client sdk -key FlashCount -value "13" -context "sdk\\\\bsp/1535061192852"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1535061192852"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1535061192852"
webtalk_transmit -clientid 3762438862 -regid "" -xml C:\\Users\\Chinook-ELE\\ZynqWorkspace\\SensTel2_emio_NNip\\nn_ip_addition\\rtos_emio_port_NN_rev4_but_after_rev5\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\Chinook-ELE\\ZynqWorkspace\\SensTel2_emio_NNip\\nn_ip_addition\\rtos_emio_port_NN_rev4_but_after_rev5\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\Chinook-ELE\\ZynqWorkspace\\SensTel2_emio_NNip\\nn_ip_addition\\rtos_emio_port_NN_rev4_but_after_rev5\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
