set_property SRC_FILE_INFO {cfile:C:/Users/Chinook-ELE/ZynqWorkspace/real_ip_tmr_test/ip_tmr_test.srcs/constrs_1/new/MiniZed_PS_SPI.xdc rfile:../../../ip_tmr_test.srcs/constrs_1/new/MiniZed_PS_SPI.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R10 [get_ports capturetrig0]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P10 [get_ports capturetrig1]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L15 [get_ports UART_0_rxd]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M15 [get_ports UART_0_txd]
